name = "MCPTrajectoryGameSolver"
uuid = "d93e73c3-c101-4c3f-b101-f812c3e47675"
authors = ["lassepe <lasse.peters@mailbox.org>"]
version = "0.1.1"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
MixedComplementarityProblems = "6c9e26cb-9263-41b8-a6c6-f4ca104ccdcd"
TrajectoryGamesBase = "ac1ac542-73eb-4349-ae1b-660ab3609574"

[compat]
BlockArrays = "0.16, 1"
ChainRulesCore = "1"
MixedComplementarityProblems = "0.1.9"
TrajectoryGamesBase = "0.3.6"
julia = "1.7"
